### ISSUE TITLE
CI Setup

### ISSUE THREAD

**Issue by pgmanutd** [rrenny/react-pwa-boilerplate#2]
- [ ] Add CI script using github actions. Refer [this file](https://github.com/pgmanutd/react-accessibility-tools-integration/blob/master/.github/workflows/ci.yml) for ci script. Please replace in above file:

```yml
- name: Build code
        run: yarn build
        env:
          CI: true

- name: Run lighthouse audit
  run: yarn test:lh-ci

- uses: actions/upload-artifact@v2
  with:
    name: lighthouseci-audits
    path: .lighthouseci
```

with

```yml
- name: Verify code
        run: yarn run check
        env:
          CI: true

- uses: actions/upload-artifact@v2
  with:
    name: coverage
    path: coverage
```

and add

```yml
- name: Use Node.js ${{ matrix.node-version }}
  uses: actions/setup-node@v1
  with:
    node-version: ${{ matrix.node-version }}
```

after this step: `- uses: actions/checkout@v2` 

- [ ] Add badge. Refer [this commit](https://github.com/pgmanutd/recipes/commit/9507f9e1c8adcee75594e2173202ed7ab7be217a)
