### ISSUE TITLE
CD Setup

### ISSUE THREAD

**Issue by pgmanutd** [rrenny/react-pwa-boilerplate#3]
- [ ] Link current repo with netlify

- [ ] Add `cd.yml` file in `.github/workflows` folder. File can be as follows

```yml
name: CD

on:
  push:
  pull_request:
      types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build code
        run: yarn build
        env:
          CI: true

      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
```

Configure `NETLIFY_AUTH_TOKEN` and `NETLIFY_SITE_ID` in `https://github.com/rrenny/react-pwa-boilerplate/settings/secrets`. 

Refer this action for more details about above script and tokens: https://github.com/marketplace/actions/netlify-actions
